### ISSUE TITLE
Add library call.

### ISSUE THREAD

**Issue by iangow** [zerogetsamgow/victax#1]
I think you're missing `library(duckdb)` (so not sure how this works).

You can use `duckdb::tbl_file()` to read a parquet file directly. You might check out performance just using `arrow` in place of `dplyr` data frames in terms of performance.

https://github.com/zerogetsamgow/victax/blob/e89a6d29a18c5d3daa014c949b9109972f050761/app.R#L19

**Comment by zerogetsamgow** [comment]
It is in the local version. I will push it to here next week.

**Comment by iangow** [comment]
Note that `arrow::read_parquet()` (and subsequent steps using Arrow) is faster, but still a few seconds. So DuckDB seems better (less than a second will feel snappy). It's probably like those early episodes of the Netflix series about Spotify … they were obsessive about lags.
